authors:
  mads:
    name: Mads Bech-Wilumstad
    description: Nest leder
    # avatar: https://github.com/squidfunk.png
    avatar: https://github.com/lewiuberg/forza-arendal/blob/master/docs/assets/images/blog/profile/mads.png
