authors:
  mads:
    name: Mads Bech-Wilumstad
    description: Nest leder
    avatar: https://raw.githubusercontent.com/lewiuberg/forza-arendal/refs/heads/master/docs/assets/images/blog/profile/mads.png
