authors:
  official:
    name: Forza Arendal
    description: Offisiell kungjøring fra Forza Arendal
    avatar: https://raw.githubusercontent.com/lewiuberg/forza-arendal/refs/heads/master/docs/assets/images/blog/profile/forza-official.png
  mads:
    name: Mads Bech-Wilumstad
    description: Nest leder
    avatar: https://raw.githubusercontent.com/lewiuberg/forza-arendal/refs/heads/master/docs/assets/images/blog/profile/mads.png
  lewi:
    name: Lewi Uberg
    description: Sosiale medier og web
    avatar: https://raw.githubusercontent.com/lewiuberg/forza-arendal/refs/heads/master/docs/assets/images/blog/profile/lewi.JPG
  lene_victoria:
    name: Lene Victoria
    description: Supporter og skribent
    avatar: https://raw.githubusercontent.com/lewiuberg/forza-arendal/refs/heads/master/docs/assets/images/blog/profile/lene-victoria.JPG
  mads_lewi:
    name: Mads Bech-Wilumstad & Lewi Uberg
    description: Samarbeid
    avatar: https://raw.githubusercontent.com/lewiuberg/forza-arendal/refs/heads/master/docs/assets/images/blog/profile/mads_lewi.png
