authors:
  mads:
    name: Mads Bech-Wilumstad
    description: Nest leder
    avatar: https://raw.githubusercontent.com/lewiuberg/forza-arendal/refs/heads/master/docs/assets/images/blog/profile/mads.png
  lewi:
    name: Lewi Uberg
    description: Fullstack utvikler, og supporter
    avatar: https://raw.githubusercontent.com/lewiuberg/forza-arendal/refs/heads/master/docs/assets/images/blog/profile/lewi.JPG
  mads_lewi:
    name: Mads Bech-Wilumstad & Lewi Uberg
    description: Samarbeid
    avatar: https://raw.githubusercontent.com/lewiuberg/forza-arendal/refs/heads/master/docs/assets/images/blog/profile/mads_lewi.png
