name: Run Markdown Generator

on:
  schedule:
    - cron: "0 20 * * *" # Runs every day at 20:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: |
          uv sync --all-groups --frozen
          uv pip install -r backend/requirements.txt

      - name: Discard any lock file changes
        run: git checkout -- uv.lock || true

      - name: Run tables pipeline script
        run: uv run python backend/tables_pipeline.py

      - name: Commit changes from tables pipeline
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/assets/tables/*
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update tables [skip ci]"
            git pull --rebase origin master
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run markdown generator script
        run: uv run python backend/markdown_generator.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/tabell.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update tabell.md [skip ci]"
            git pull --rebase origin master
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
