name: Run Markdown Generator

on:
  schedule:
    - cron: "55 20 * 3-10 *" # Runs at 20:55 UTC during daylight saving time (March to October)
    - cron: "55 21 * 11-2 *" # Runs at 21:55 UTC during standard time (November to February)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      #   - name: Install dependencies
      #     run: pip install -r requirements.txt

      - name: Run markdown generator script
        run: python backend/markdown_generator.py
